/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linkedlist;


import org.junit.*;

import java.util.ArrayList;
import java.util.List;

import static org.junit.Assert.*;


public class LinkedListTest {
    @Test public void testInsert() {
        LinkedList list = new LinkedList();
        list.insert("Something");
        assertTrue(list.head.value == "Something");
    }

    @Test public void testIncludes_true(){
        LinkedList list = new LinkedList();
        list.insert("Something");
        assertEquals("Should return boolean true when linked list has the value", true, list.includes("Something"));
    }

    @Test public void testIncludes_false(){
        LinkedList list = new LinkedList();
        assertEquals("Should return boolean false when linked list does not have the value.", false, list.includes(
            "Something else"));
    }

    @Test public void testPrintString(){
        LinkedList list = new LinkedList();
        list.insert("a");
        list.insert("a");
        List<String> result = new ArrayList<String>();
        result.add("a");
        result.add("a");
        assertEquals("Returns a string of all values in the linked list.", result, list.printString());
    }
}
